name: Swift Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build for iOS Simulator
        run: xcodebuild build -scheme MovieCatalogShared -destination 'platform=iOS Simulator,name=iPhone 14'

      - name: Build for macOS
        run: xcodebuild build -scheme MovieCatalogShared -destination 'platform=macOS,arch=x86_64'
